### ISSUE TITLE
Invalid UTF-8 middle byte

### ISSUE THREAD

**Issue by HalloTheEngineer** [untisapi/untis4j#20]
As my username contains a "ä", which isn't present in the UTF-8 table, i get the following error when trying to create a new Session:
`An unexpected exception occurred: {"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error: Invalid UTF-8 middle byte 0x48\n at [Source: (com.grupet.web.filter.XSSProtectionFilter$MultiReadHttpServletRequest$CachedServletInputStream); line: 1, column: 89]"}}`
I believe the fault lies here on the part of the server, i. e. WebUntis. Is there nevertheless a way to circumvent the error?

**Comment by maxmielchen** [comment]
Unfortunately, I have no way of reproducing this scenario. Have you already tried replacing the ä with ae? If that works, I could implement it in the login in such a way that 'umlaute' are replaced by the associated spelling.

**Comment by HalloTheEngineer** [comment]
Unfortunately, this didn't work. The server returned code -8504, "bad credentials". 
To reproduce the scenario:
I used the [code snippet](https://github.com/untisapi/untis4j#simple-timetable) which is shown on the read-me page, filled in my credentials (which are working with a JS Api) and started the program via IntelliJ.

**Comment by maxmielchen** [comment]
As I said, I can't reproduce this scenario because I don't have an untis account with an ä, ü or ö in the user name. It would be very helpful if, instead of just giving an exception, you also give the piece of code where this error occurs. So that I can better understand what's causing this problem and make sure you're not just misusing this library. Also, I think you didn't give me the full exception because you can only see a small part of the exception trigger chain. So I'm asking you to give me the full exception and the part of your code where this exception is thrown.

**Comment by HalloTheEngineer** [comment]
Sure, here it is:
[Pastebin](https://pastebin.com/MpuQtV81)
